jobs:

- job: 'i686_macos_clang'
  condition: eq(1, 2)
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      git clone https://github.com/ariya/compression-corpus.git
      cd compression-corpus
      cd enwik
      unzip enwik8.zip
    displayName: 'Retrieve test compression corpus'
  - script: cc --version
    displayName: 'Verify tools version'
  - script: make roundtrip CFLAGS='-m32' LDFLAGS='-m32'
    workingDirectory: tests
    displayName: 'Perform round-trip tests'
  - script: file tests/test_roundtrip
    displayName: 'file tests/test_roundtrip'
  - script: make CFLAGS='-m32' LDFLAGS='-m32'
    workingDirectory: examples
    displayName: 'Build examples: 6pack and 6unpack'
  - script: |
      file ./6pack
      ./6pack -v
      ./6pack ../compression-corpus/enwik/enwik8.txt archive.6pk
      file ./6unpack
      ./6unpack -v
      ./6unpack archive.6pk
    workingDirectory: examples
    displayName: 'Run examples: 6pack and 6unpack'

- job: 'i686_macos_gcc'
  condition: eq(1, 2)
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      git clone https://github.com/ariya/compression-corpus.git
      cd compression-corpus
      cd enwik
      unzip enwik8.zip
    displayName: 'Retrieve test compression corpus'
  - script: brew install gcc@9
    displayName: 'Install requirements'
  - script: gcc-9 --version
    displayName: 'Verify tools version'
  - script: CC=gcc-9 make roundtrip CFLAGS='-m32' LDFLAGS='-m32'
    workingDirectory: tests
    displayName: 'Perform round-trip tests'
  - script: file tests/test_roundtrip
    displayName: 'file tests/test_roundtrip'
  - script: CC=gcc-9 make CFLAGS='-m32' LDFLAGS='-m32'
    workingDirectory: examples
    displayName: 'Build examples: 6pack and 6unpack'
  - script: |
      file ./6pack
      ./6pack -v
      ./6pack ../compression-corpus/enwik/enwik8.txt archive.6pk
      file ./6unpack
      ./6unpack -v
      ./6unpack archive.6pk
    workingDirectory: examples
    displayName: 'Run examples: 6pack and 6unpack'
